# Enable the build cache to save time by reusing outputs produced by other successful builds.
# https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
# Enable the configuration cache to reuse the build configuration and enable parallel task execution.
# (Note that some plugins may not yet be compatible with the configuration cache.)
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8

# Advent of Code session cookie
systemProp.AOC_SESSION=53616c7465645f5f0cd0a01c2743afce87a7b45e4e405990e8d0a66e2023390a4185f85f801b62bb34b1b98508eac645e2d15851e8769dcd3061e5df270ed1ae
